version: '3.8'
services:
  app:
    build: .
    user: ${UID}
    volumes:
      - ./:/var/www/html/
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    ports:
      - "80:80"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: motos
    volumes:
      - ./database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"